services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pronoundb
      POSTGRES_PASSWORD: seekwet!
      POSTGRES_DATABASE: pronoundb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
